import Head from "next/head";
import Image from "next/image";
import { Toolbar } from "../components/toolbar";
import styles from "../styles/Home.module.css";

const api_key = "82e119b1e01441c1b08417d9c5bb3df7";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/x-icon" href="/public/favicon.ico" />
        <link rel="shortcut icon" href="/favicon/favicon.ico" />
      </Head>

        <Toolbar />
      <div className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </div>
    </div>
  );
}
